FROM ubuntu:latest
RUN apt install java-11-openjdk -y
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz .
RUN tar -xvf apache-tomcat-8.5.99.tar.gz -C /opt
WORKDIR /opt/apache-tomcat-8.5.99
COPY context.xml conf/context.xml 
COPY student.war apache-tomcat-8.5.99/webapps/ . 
COPY mysql-connector.jar apache-tomcat-8.5.99/lib/ .
ENTRYPOINT [ "bin/catalina.sh" ]
CMD [ "start" ]
